### ISSUE TITLE
Template Haskell embed file / directory dependencies

### ISSUE THREAD

**Issue by bergey** [judah/pier#136]
Trying out `pier`, I encounter the following error:

```
Error when running Shake build system:
* Library diagrams-rasterific
* Command: diagrams-rasterific-1.4.2: building library

_pier/artifact/external/src/Diagrams/Backend/Rasterific/Text.hs:79:9: error:
    • Exception when trying to run compile-time code:
        fonts: getDirectoryContents:openDirStream: does not exist (No such file or directory)
      Code: embedDir "fonts"
    • In the untyped splice: $(embedDir "fonts")
   |
79 | fonts = $(embedDir "fonts")
   |         ^^^^^^^^^^^^^^^^^^^
```

Running with `-V --keep-temps`, I think `pier` is sandboxing the build of `Text.hs`, and is unaware of the file's dependence on the `fonts` directory.  Do you have thoughts on how to support these dependencies?

This `$(embedFile)` pattern is important for my eventual production use of `Shake` / `pier`.  I'd be fine giving `pier` some guidance, maybe even an explicit list of additional dependencies.  Or embedding the Shake rules that `pier` provides in a custom Shakefile of my own, so I can write whatever other rules I need.  In that case I probably will try a rule that searches Haskell files for calls to `$(embedFile)` - get my money's worth from Shake's dynamic dependencies.

**Comment by judah** [comment]
Thank you for the report.  Currently, Pier *does* support supplying files for TemplateHaskell in that manner, but only if they're specified in the "extra-source-dirs" of the .cabal file.  diagrams-rasterific specifies them in data-files, which is why it doesn't compile.  (For what it's worth, that seems like an
incorrect use of data-files --- if we're embedding the files, then they shouldn't need to be installed.)

Probably for compatibility we should make data-files available for compilation too.  In the meantime, for your own packages, you should be able to use `extra-source-dirs` to feed files into TemplateHaskell.

**Comment by bergey** [comment]
Thanks, that makes sense.  I confirmed that `diagrams-rasterific` works if I add the fonts to `extra-source-files`.  

FWIW, I agree with you that `extra-source-files` would be more appropriate; I think this is a relic of a version that loaded the fonts at runtime.
